import random

# List of RBRPro2 stages
stages = [
    "Ai-petri 1",
    "Akkaharju 0",
    "Alahala 2",
    "Alakyla sprint 3",
    "Alakkyla vidrike Lai 3",
    "Alakkyla vidrike kargula 3",
    "Allemagne Shakedown 2011 0",
    "Alsace 2",
    "Ambohimanarina 3",
    "Ambrosian hills 0",
    "Amorondrano 3",
    "Anavasi pentelis hillclimb 0",
    "Argentine Shakedown 2011 1",
    "Assergi 1",
    "Bevalala piste 2",
    "Brandenbourg 0",
    "Brooks 2013 0",
    "Caroya 2",
    "Cassidy 0",
    "Cenovio valeron 2",
    "Cezas 0",
    "Chamrousse 0",
    "Circuit ACCT Ivato 1",
    "Citta dei Mille 0",
    "Col de vaux 0",
    "Col de buc 0",
    "Colle sant eusebio 1",
    "Colognac 2022 0",
    "Corian 1",
    "Craig Breen tribute 2",
    "Daniel bonara 0",
    "Ehikki 1",
    "El vellon 0",
    "Essay circuits des ducs 0",
    "Estadio algarve 0",
    "Estadio cordoba 0",
    "Fafe rally sprint 1",
    "Faleyras autocross 3",
    "Folkrace 2",
    "Forest trip 2",
    "Fressac 1",
    "Gran sasso 1",
    "Gymkhana Ken block tribute 0",
    "Haanja kokemae 1",
    "Haanja kurgjarve 1",
    "Haanja Ristee 1",
    "Hakmark 2023 1",
    "Hakolahti sprint 1",
    "Haltia luopioinen 2",
    "Hanaa 2",
    "Harmanmaki 2",
    "Hazlach barborka cieszynska 3",
    "Hebecrevon 1",
    "Hollebeke 1",
    "Hondarribia 3",
    "Horkka 3",
    "Hygget 3",
    "Ilmalanmaki 2",
    "Industry 3",
    "Ircio 02 1",
    "Juncalillo 3",
    "Jyvaskylan pienoisralli 2",
    "Kamen 3",
    "Kanniranni 3",
    "Kippinge 3",
    "Konttivuori 2",
    "La bouvante le pionnier 3",
    "La iglesuela 0",
    "Lac du cerf 2",
    "Lampikannas 2",
    "Las majadas 1",
    "Las vueltas 0",
    "Laukkajoki 3",
    "Limbo 3",
    "Loveland pass 2",
    "Luceram printemps 3",
    "Lydden hill 1",
    "Maasmechelen 1",
    "Majbana 3",
    "Malaga a7000 hillclimb 3",
    "Mangalanitra 3",
    "Markim 2",
    "Martin Luis 1",
    "Maungatawhiri 2",
    "Mexico Shakedown 3",
    "Mokkipera 2",
    "Mount Herman 2",
    "Mountain road winter 1",
    "Mussara ?",
    "Mysingen 2",
    "NZ Shakedown 0",
    "Noidant 2",
    "Nokkopohja koivulahti 3",
    "Non Khom 3",
    "Nordschleife 2",
    "Ostra eka 2",
    "Oulu rallycross 4",
    "Perrogney 2",
    "Philippe wambergue 2",
    "Piornal 1",
    "Pohjanmaa ralli ek2 2",
    "Polja sprint 2",
    "Quebec faustin 2",
    "Rally wisla zamarski 2",
    "Rally sprint i.g. 1",
    "Ritsona 3",
    "Rozmital 96 1",
    "Rubbio 1",
    "Ruoveden helvetti 2",
    "SS Kullilampi 2",
    "Saaristo 2",
    "Saint Agreve 1",
    "Sambro 1",
    "San Marcial 1",
    "Slomczyn rallycross 3",
    "Slusovice rs 3",
    "Soudorgues 2",
    "Spain Shakedown 2011 2",
    "Stryckovy okruh 3",
    "Sweden Shakedown 2",
    "Tale of the dragon 1",
    "Test track academy 2",
    "The creek 0",
    "The w 2",
    "Thirimont Bianchi 0",
    "Ticksta sprinten 1",
    "Tuna 3",
    "Uppland 3",
    "Urria 2",
    "Uskila 2",
    "Vale Judeu 1",
    "Vertnex Szlalom 1",
    "Vontovorona 1",
    "Waimai valley 2021 2",
    "Waipu gorge 0",
    "Westourer 1",
    "Whaanga coast 0",
    "Ypres Shakedown 0",
    "Zelezniki 3"
]

# Sample car list (modify with your faves)
cars = [
    "Subaru Impreza WRC",
    "Mitsubishi Lancer Evo VII",
    "Peugeot 206 WRC",
    "Citroën Xsara WRC",
    "Hyundai Accent WRC",
    "MG ZR Super 1600",
    "Subaru Impreza 2000",
    "Ford Focus WRC",
    "Toyota Celica GT-Four",
    "Lancia Delta Integrale",
    "Audi Quattro",
    "Ford Escort RS Cosworth",
    "Renault 5 Turbo",
    "Skoda Fabia WRC",
    "Mini Cooper S",
    "Volkswagen Polo R WRC",
    "Mitsubishi Lancer Evo VI",
    "Subaru Legacy RS",
    "Toyota Yaris WRC",
    "Fiat 131 Abarth"
]

# List of weather conditions
weather_conditions = [
 
    "Clear",
    "Cloudy",
    "Overcast",
    "Light Rain",
    "Heavy Rain",
    "Thunderstorm",
    "Snow",
    "Fog"
]

# Function to get a random stage, car, and weather condition
def randomize_rbr_daily():
    stage = random.choice(stages)
    car = random.choice(cars)
    weather = random.choice(weather_conditions)
    return stage, car, weather

# Run the function and print the result
stage, car, weather = randomize_rbr_daily()
print(f"Stage: {stage}")
print(f"Car: {car}")
print(f"Weather: {weather}")

